import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "@/presentation/components/ui/navbar/page";
import { ThemeProvider } from "@/presentation/components/providers/darkMode";
import "public/css/embla/embla.css";
import "public/css/embla/base.css";
import "public/css/global.css";
import HomeComp from "@/presentation/components/pages/home/page";

const generalSans = localFont({
  src: [
    {
      path: "../fonts/GeneralSans-Variable.ttf",
      weight: "100 900",
      style: "normal",
    },
    {
      path: "../fonts/GeneralSans-VariableItalic.ttf",
      weight: "100 900",
      style: "italic",
    },
  ],
  variable: "--font-general-sans",
});

const clashDisplay = localFont({
  src: "../fonts/ClashDisplay-Variable.ttf",
  weight: "100 900",
  style: "normal",
  variable: "--font-clash-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${generalSans.variable} ${clashDisplay.variable} min-h-screen font-sans antialiased `}>
        <ThemeProvider>
          <Navbar />
          <HomeComp className=""></HomeComp>
        </ThemeProvider>
      </body>
    </html>
  );
}
